### ISSUE TITLE
Renaming this repo to String.prototype.padEnd

### ISSUE THREAD

**Issue by brandonpayton** [es-shims/String.prototype.padEnd#1]
Hi, should this repo be renamed to "String.prototype.padEnd" as it is linked to in the spec [README](https://github.com/tc39/proposal-string-pad-start-end/blob/f20742ba64026ced18a2d6133b0c07922c84630c/README.md)?

**Comment by ljharb** [comment]
Thanks, I must have forgotten this one in all the renaming flurry!
